version: "3.9"
services:
  dbf:
    image: postgres
    container_name: dbf
    environment:
      - POSTGRES_DB=forum_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./dbf/forum_db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  app:
    image: dima202020/job4j_forum
    container_name: job4j_forum
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbf:5432/forum_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - dbf